### ISSUE TITLE
Reducing the packages size: disable src and dest 16 bytes

### ISSUE THREAD

**Issue by musgravehill** [jgromes/LoRaLib#15]
The main idea: disable Src and Dest addresses and save 16 bytes.  It is important for slow baudrate on long distance. 300bps or 1200bps... 

For example, I put devicies addresses in to Payload and encrypt them. And I completely use EEPROM for other purposes. 

As I can see:  Lora.begin(,,,,bool isUseSrcDestAddrs)
if (isUseSrcDestAddrs == false)   => no EEPROM usage, small Package with payload only.
if (isUseSrcDestAddrs == true)   => EEPROM usage, Package with Src, Dest, Payload.

**Comment by jgromes** [comment]
I was thinking about dropping the Packet class completely for a while now. Since I never got around to implement any sort of address-based filtering, having the Packet class doesn't add anything new.

This would require changing receive and transmit methods to work with C-strings and then maybe add overloads for byte arrays and Arduino String class. If you're up for the task, I will gladly accept any help you can give me :)

Also, another benefit would be the ability to add LoRaWAN support in KiteLib.

**Comment by musgravehill** [comment]
Jan Gromeš, thank you for lib! 
Im not true software designer, Im arduino-style. So, I will try to help you "as is". 
I see 2 ways:
0. Lora.print(String, int, 'char',  float[,decimals]) like Serial.print()  - emulate Serial modem
1. Lora.send(array of int ([u]int8.16.32, array size in bytes) - emulate NRF style, good choise for telemetry data, no need parsing incoming string. "array size in bytes" array[2] of int16 => 2 * 2bytes = 4 bytes. 

So, if I need send some string or custom data - select Lora.print()
If I need to send the structure with data normalized to int** - select Lora.send()

**Comment by jgromes** [comment]
I'm probably going to leave the current naming/return conventions as they are:

`LoRa::transmit(const char* str);` to send C-string,
`LoRa::transmit(String& str);` to send Arduino String,
`LoRa::transmit(uint8_t* str, size_t len);` to send arbitrary byte array.

What do you think about this?

On a side note, this breaks backwards compatibility, so I will have to release it as v3.0.0 - didn't think I would have to do that less than a week after v2.0.0 :)

**Comment by musgravehill** [comment]
I agree with you! 
I forgot about backwards compatibility.. 
`LoRa::transmit(uint8_t* str, size_t len);` can be used for telemetry data, it will need some shift to get data0, data1, etc from arbitrary byte array.

**Comment by jgromes** [comment]
The new methods will be on [remove-packet](https://github.com/jgromes/LoRaLib/tree/remove-packet) branch, so you can test it out before the release.

So far the transmit method is done and should be working, I'll let you know when the receive method works as well.

**Comment by musgravehill** [comment]
Thank you!
I ordered Lora RA-02 SX1276 and waiting for it...

**Comment by jgromes** [comment]
Everything is updated in the branch. It didn't take as much testing as I anticipated, so I'll just merge that branch and release v3.0.0. Feel free to reopen this issue if you have any more questions.
