### ISSUE TITLE
Arduino ATmega328 d10 for NSS

### ISSUE THREAD

**Issue by musgravehill** [jgromes/LoRaLib#19]
Can I use arduino pin d10 for NSS? The d10 is default chip-select pin for hardware SPI. Is it interference with LoRaLib code?

**Comment by jgromes** [comment]
Unless you want to use the Arduino as SPI slave, D10 is just a normal digital IO pin. So yes, you can use it NSS for LoRaLib.

**Comment by musgravehill** [comment]
Jan, thank you for answer!
