### ISSUE TITLE
SX1272 fails to initialize

### ISSUE THREAD

**Issue by bibaswan** [jgromes/LoRaLib#20]
**Describe the bug**
When trying to initialize the LoRa Semtech sx1272 board the program throws error code 0x1 after 2 seconds of showing initializing.
 
**To Reproduce**
run default transmit example using settings from screenshot or any other combination of pins for the NCC, DIO0, DIO1

**Expected behavior**
trying to run default example at 868 MHz but get error code 0x1

**Screenshots**
<img width="592" alt="screen shot 2018-07-18 at 09 01 00" src="https://user-images.githubusercontent.com/7562492/42868155-817c2734-8a69-11e8-8ca0-c57e5aed974c.png">
<img width="443" alt="screen shot 2018-07-18 at 09 01 03" src="https://user-images.githubusercontent.com/7562492/42868161-842b50fe-8a69-11e8-853a-68a4b00ff253.png">

**Additional info (please complete):**
 - MCU: Arduino NANO ATmega328p
 - LoRa module type SX1272
 - Arduino IDE version  1.8.1
 - Library version 3.0.1

**Comment by jgromes** [comment]
Could you try connecting your SX1272 to the default pins (NSS -> 7, DIO0 ->2, DIO1 -> 3)? Then try to run the example with default constructor `SX1272 lora = new LoRa;`

 If the problem presists there might be a fault in your wiring; if it goes away there's something wrong in the library.

**Comment by bibaswan** [comment]
<img width="168" alt="screen shot 2018-07-18 at 09 30 58" src="https://user-images.githubusercontent.com/7562492/42869553-4d6af246-8a6d-11e8-9ce3-735526dfbafc.png">

here is the output I have checked my wiring again and it seems to be all fine.

**Comment by jgromes** [comment]
Thanks for the bug!

It is fixed in release 3.0.2. Since it will take a few hours until Arduino Library Manager detects the new version, you can just download the source from [here](https://github.com/jgromes/LoRaLib/releases/tag/3.0.2)

**Comment by bibaswan** [comment]
thanks for the quick fix really appreciate it, you've helped out on a big project.
