### ISSUE TITLE
Tutorial for Sx1272

### ISSUE THREAD

**Issue by bibaswan** [jgromes/LoRaLib#21]
**IMPORTANT: Check the wiki**
Before submitting new issue, please check the [Wiki](https://github.com/jgromes/LoRaLib/wiki). You might find a solution to your issue there.

**Is your feature request related to a problem? Please describe.**
I found it very hard and time consuming to figure out how to get my Sx1272 boards to work properly with the Arduino this library really helped me out and I would like to make a detailed tutorial for the task and add it to the wiki so that other people who maybe looking for a similar solution can find it easily.

**Comment by jgromes** [comment]
Thank you for the offer, but I'm not sure that's necessary - the examples are all pretty self-exaplanatory, at least in my opinion.
