### ISSUE TITLE
sx1276/77/78 errata

### ISSUE THREAD

**Issue by pheex** [jgromes/LoRaLib#22]
Hi,

Are you aware of this ?
https://www.semtech.com/uploads/documents/sx1276_77_78-errata.pdf

**Comment by jgromes** [comment]
When writing the library, I used revision 5 of the SX1278 datasheet, dated August 2016. This errata is dated September 2013, so everything in the datasheet *should* already be fixed. I'll double-check though. Thanks for the tip!

**Comment by pheex** [comment]
The errata note still on the sx1278 ressource page 
https://www.semtech.com/products/wireless-rf/lora-transceivers/SX1278

And i don't see any use of register 0x36 and 0x3a (errata 2.1) in rev 5 datasheet, so i don't know if they managed errata another way.

**Comment by jgromes** [comment]
2.1 - Seems like an easy fix.
2.2 - Errata doesn't provide any workaround.
2.3 - Seems fixable as well.
2.4 - LoRaLib doesn't use the counter, so no need to fix that.
3.x - LoRaLib doesn't use FSK modem, no need to fix that either.

It'll be fixed it in the next release, probably tomorrow.

**Comment by pheex** [comment]
ok, thank you

**Comment by jgromes** [comment]
Fixed in release 3.0.3. I tested fixes for 2.1 and 2.3, both should be working fine.
