### ISSUE TITLE
Short distance, low power RF, low power consumption

### ISSUE THREAD

**Issue by musgravehill** [jgromes/LoRaLib#23]
I have 2pc AI-thinker LoRa RA-02 SX1278 and 2 Arduino Pro Mini 3.3V 8MHz. 
I use Update 3.0.3 release. 
All time I set infinite transmission in LOOP. 

I set power 14dBm and measure on power-meter 0.8dBm only. The LoRa consumes a current about 20mA 3.3V.
And I get short distance about some meters. 

Then I try another lib called "LoRa", I set the same config 14dBm and get the real 12dBm on power-meter, and my device consumes about 40mA. And distance has increased. 

Can there be problems with the power configuration?  Difference in distance - the main fact. mA-meter and power-meter may depend on the duty factor. But distance - no.

**Comment by musgravehill** [comment]
I try new release 4.0.0. The problem still exists.

**Comment by jgromes** [comment]
Can you post link to the other library you have used?

**Comment by musgravehill** [comment]
https://github.com/sandeepmistry/arduino-LoRa

**Comment by jgromes** [comment]
Could you please open the file `src/modules/SX1278.cpp` and replace the contents of method `SX1278::setOutputPower` (line 225) with the following code?

```
if(!(((power >= -3) && (power <= 17)) || (power == 20))) {
    return(ERR_INVALID_OUTPUT_POWER);
  }
  
  // set mode to standby
  SX127x::standby();
  
  int16_t state;
  if(power < 2) {
    // power is less than 2 dBm, enable PA on RFO
    state = _mod->SPIsetRegValue(SX127X_REG_PA_CONFIG, SX127X_PA_SELECT_RFO, 7, 7);
    state |= _mod->SPIsetRegValue(SX127X_REG_PA_CONFIG, SX1278_LOW_POWER | (power + 3), 6, 0);
    state |= _mod->SPIsetRegValue(SX1278_REG_PA_DAC, SX127X_PA_BOOST_OFF, 2, 0);
  } else if((power >= 2) && (power <= 17)) {
    // power is 2 - 17 dBm, enable PA1 + PA2 on PA_BOOST
    state = _mod->SPIsetRegValue(SX127X_REG_PA_CONFIG, SX127X_PA_SELECT_BOOST, 7, 7);
    state |= _mod->SPIsetRegValue(SX127X_REG_PA_CONFIG, SX1278_MAX_POWER | (power - 2), 6, 0);
    state |= _mod->SPIsetRegValue(SX1278_REG_PA_DAC, SX127X_PA_BOOST_OFF, 2, 0);
  } else if(power == 20) {
    // power is 20 dBm, enable PA1 + PA2 on PA_BOOST and enable high power mode
    state = _mod->SPIsetRegValue(SX127X_REG_PA_CONFIG, SX127X_PA_SELECT_BOOST, 7, 7);
    state |= _mod->SPIsetRegValue(SX127X_REG_PA_CONFIG, SX1278_MAX_POWER | (power - 5), 6, 0);
    state |= _mod->SPIsetRegValue(SX1278_REG_PA_DAC, SX127X_PA_BOOST_ON, 2, 0);
  }
  
  return(state);
```

Try measuring the draw current again, see if this improves it.

**Comment by musgravehill** [comment]
It works! 
"10" -> 30mA
"14" -> 38mA
"17" -> 48mA
I set power 10 and get 9dBm (connectrors loss, instrumental error), it works! 
![img_20180725_091122](https://user-images.githubusercontent.com/1556167/43182824-9db45ed0-8feb-11e8-8b42-978779b6142e.jpg)

**Comment by musgravehill** [comment]
=) 

`lora.begin(434.6, 125, 12, 8, 0x15, 20);` gives 17.54dBm 

I paid attention to SWR and used attenuator for not to burn the device.
I used calibrated on industrial metrology equipment power-meter from here http://forum.rcdesign.ru/blogs/1628/blog22370.html 
It seems very accurate. So, Im trust in it.

**Comment by musgravehill** [comment]
On the cover it says 18dBm.  
![ra-02-sx1278-433 jpg_640x640](https://user-images.githubusercontent.com/1556167/43183539-22e437cc-8fee-11e8-935f-7350db175963.jpg)

**Comment by jgromes** [comment]
It might be the SX1278's overcurrent protection kicking in, I'll create a separate issue for that.
I'll fix this issue in release 4.0.1

**Comment by musgravehill** [comment]
Ok, thank you!
I asked AI-thinker about max power. They replied 18dBm.

**Comment by jgromes** [comment]
SX1278 should be able to output 20 dBm (at 1% duty cycle and 3:1 voltage SWR at antenna), but it's hard to guess what other components are there under the metal case and how will they affect the performance.

**Comment by musgravehill** [comment]
This is a Chinese lottery...

**Comment by jgromes** [comment]
Yeah :)

Update 4.0.1 is live, thanks for reporting the bug. I also made another issue for the OCP, but I'm probably going to have to build a power meter too if I want to add that feature.
