### ISSUE TITLE
Support for the SX126X transceivers

### ISSUE THREAD

**Issue by IoTInsights** [jgromes/LoRaLib#28]
Semtech has announced the new generation of transceivers at the beginning of the year. Do you have plans to support the SX126X series as well?

At the moment it doesn't seem to be an issue as I haven't seen any modules with SX126X transceivers, yet.

**Comment by IoTInsights** [comment]
Thanks for the info. Let's see when the modules will be available.

**Comment by jgromes** [comment]
My main reason for keeping LoRaLib SX127x-only is because these modules are by far the most popular LoRa modules.

I'm closing the issue for now, feel free to re-open later.
