### ISSUE TITLE
CAD detection

### ISSUE THREAD

**Issue by IoTInsights** [jgromes/LoRaLib#29]
Looking at the API documentation, I haven't found any support for CAD (Channel Activity Detection). Do you have any plans to add this feature to the library?

**Comment by jgromes** [comment]
LoRaLib has CAD support; see [ChannelActivityDetection](https://github.com/jgromes/LoRaLib/blob/master/examples/ChannelActivityDetection/ChannelActivityDetection.ino) example

**Comment by IoTInsights** [comment]
Thanks for the quick response. Sorry that I have missed it going through the docs.
