### ISSUE TITLE
Incorrect maximum sync word size

### ISSUE THREAD

**Issue by juliantech5** [jgromes/LoRaLib#39]
Using the FSK modem test example the following error is received from the serial monitor.
`Initializing ... success!
Unable to set configuration, code -24
`

All connections are attached (including additional pin 4 clock cable)

Any ideas?

**Comment by jgromes** [comment]
There was an incorrect constraint on the sync word size in `setSyncWord` function.
Workaround: use maximum 7 byte long sync word.

**Comment by jgromes** [comment]
Fixed in update 5.2.1, thanks for reporting!
