### ISSUE TITLE
Code Error FFE8

### ISSUE THREAD

**Issue by juliantech5** [jgromes/LoRaLib#42]
We are currently experimenting with RTTY and FSK,
the following code appears 
`(SWITCH FSK MODE)
Unable to set configuration, code ffe8
(COMM SYSTEM END
(SWITCH LORA MODE)
`
LoRa works fine but FSK does not work, DIO2 Is hooked up to D10 (and declared to d10)

Any ideas? Will try another Transmitter now.

**Comment by jgromes** [comment]
The codes are returned as 16 bit signed numbers, could you please print it as such?

**Comment by juliantech5** [comment]
Code -24

**Comment by jgromes** [comment]
https://github.com/jgromes/LoRaLib/wiki/Error-Codes

-24 is invalid sync word. FSK sync word must not be longer than 8 bytes and must not contain any null bytes (0x00)

**Comment by juliantech5** [comment]
Ah! Same Issue as before.
Sorry mate!
Thanks

**Comment by juliantech5** [comment]
Is it fixed in the example?

**Comment by jgromes** [comment]
The range check was wrong, it should be working this time.

Fixed in bdc78fe637e6dd5f00688134ad11dc7dd3b66d81
