### ISSUE TITLE
Large bandwidth in direct mode AFSK?

### ISSUE THREAD

**Issue by Bambofy** [jgromes/LoRaLib#47]
We are transmitting at 2522hz and 183hz shift with direct mode FSK. But the received output is at a bandwidth of 100khz, any ideas at what might be going wrong?

Thanks,
Richard

**Comment by jgromes** [comment]
Can you please share your code when opening issues? Then I'll be able to help you much quicker.

**Comment by Bambofy** [comment]
`#include <LoRaLib.h>
 
SX1278 lora = new LoRa;
int RTTY_BASE = 2125; // Hz
int RTTY_SHIFT = 182; //183; // 3 * 61Hz
int RTTY_BAUD_RATE = 22222; // micro-seconds (us) 45.5 baud
int DIGITAL_OUT_SX1278_DIRECT = 10;
 
void setup() {
  Serial.begin(9600);
}
 
 
//////////////////////////////////
// RTTY Protocol implementation //
//////////////////////////////////
void Communication_RTTY_TransmitMark()
{
  unsigned long start = micros(); // MICRO seconds.
 
  tone(DIGITAL_OUT_SX1278_DIRECT, RTTY_BASE - RTTY_SHIFT);
 
  while (micros() - start < RTTY_BAUD_RATE);
 
  noTone(DIGITAL_OUT_SX1278_DIRECT);
}
 
void Communication_RTTY_TransmitSpace()
{
  unsigned long start = micros(); // MICRO seconds.
 
  tone(DIGITAL_OUT_SX1278_DIRECT, RTTY_BASE);
 
 
  while (micros() - start < RTTY_BAUD_RATE);
 
  noTone(DIGITAL_OUT_SX1278_DIRECT);
}
 
void Communication_RTTY_TransmitBit(char inChar)
{
  Communication_RTTY_TransmitSpace();
 
  // for each bit in char (8-bits) (only use 7 bits)
  char m = 0x01; // mask
  int bitIndex = 0;
  for (m; m; m <<= 1)
  {
    if (bitIndex == 7) break; // ascii is 7 bit
   
    // if the char bit is selected by the mask...
    if (inChar & m)
    {
      // send a 1 (MARK) = base - shift
      Communication_RTTY_TransmitMark();
    }
    else
    {
      // send a 0 (SPACE) = base
      Communication_RTTY_TransmitSpace();
    }
   
    bitIndex++;
  }
 
  Communication_RTTY_TransmitMark();
}
 
/*
 * @brief send a string through the RTTY protocol.
 *
 * @todo check if the \r\n chars are being transmitted.
 */
void Communication_RTTY_Transmit(String inTransmissionPacket)
{
  // for each 8-bit byte/char. only 7 used in ascii?
  for (int i = 0; i < inTransmissionPacket.length(); i++)
  {
    Communication_RTTY_TransmitBit(inTransmissionPacket.c_str()[i]);
  }
}
 
void Communication_RTTY_BeginTransmission()
{
    Communication_RTTY_TransmitMark();
    delay(500);
}
 
void Communication_RTTY_EndTransmission()
{  
    Communication_RTTY_Transmit("\r\n");
    lora.packetMode();
}
 
void Communication_Transmit_ITA2_LettersShift()
{
  Communication_RTTY_TransmitSpace();
 
  // also erasure and deletion
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
 
  Communication_RTTY_TransmitMark();
}
 
void Communication_Transmit_ITA2_FiguresShift()
{
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
 
  Communication_RTTY_TransmitMark();
}
 
/*
 * @brief the ITA2 standard implementation.
 *
 * @test does capilization affect \r \n?
 */
void Communication_Transmit_ITA2_Character(char inCharacter)
{
  if (inCharacter == '\0')
  {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  }
  else if (inCharacter == '\r')
  {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  }
  else if (inCharacter == '\n')
  {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  }
  else if (inCharacter == ' ')
  {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  }
  else if (inCharacter == 'Q')
  {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'W') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'E') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'R') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'T') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'Y') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'U') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'I') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'O') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'P') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'A') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'S') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'D') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'F') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'G') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'H') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'J') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'K') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'L') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'Z') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'X') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'C') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'V') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'B') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
          Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  }
  else if (inCharacter == 'N')
  {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == 'M') {
      Communication_Transmit_ITA2_LettersShift();
 
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
     
      Communication_RTTY_TransmitMark();
  }
 
  if (inCharacter == '1') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '2') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '3') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '4') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '5') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '6') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '7') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '8') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '9') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '0') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '-') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '\'') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '!') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '&') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '£') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '(') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == ')') {
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '+') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '/') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == ':') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '=') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '?') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == ',') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitSpace();
 
      Communication_RTTY_TransmitMark();
  } else if (inCharacter == '.') {
      Communication_Transmit_ITA2_FiguresShift();
 
      Communication_RTTY_TransmitSpace();
     
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitSpace();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
      Communication_RTTY_TransmitMark();
     
      Communication_RTTY_TransmitMark();
  }
}
 
void Communication_Transmit_ITA2_Message(String inMessage)
{
  inMessage.toUpperCase();
 
  // for each character
  for (int i = 0; i < inMessage.length(); i++)
  {
    Communication_Transmit_ITA2_Character(inMessage.c_str()[i]);
  }
 
}
void loop() {
 
  Serial.println("Sending RTTY...");
  // ITA2 "RYRY" sequence.
  // LTRS R Y CR LF
 
  lora.beginFSK();
  //int state = lora.setFrequency(434);
  //state = lora.setBitRate(45.0);
  //state = lora.setFrequencyDeviation(10.0);
  //state = lora.setRxBandwidth(250.0);
  //state = lora.setOutputPower(10.0);
  //state = lora.setCurrentLimit(100);
 
  lora.transmitDirect();
 
  /* Signal to turn on terminals */
  for (int i = 0; i < 5; i++)
  {
    Communication_RTTY_TransmitMark();
  }
 
  Communication_Transmit_ITA2_Message("HELLO WORLD\r\n");
 
  /*// 0   1   0   1   0
  // lsb            msb
  // 2^0            2^4
 
  // LTRS = 1F = 11111
  // R = 0A = 01010
  // LTRS
  // Y = 15 = 10101
  // CR = 8 = 00010
  // LF = 2 = 01000
  Communication_Transmit_ITA2_Character('R');
  Communication_Transmit_ITA2_Character('Y');
  Communication_Transmit_ITA2_Character('\r');
  Communication_Transmit_ITA2_Character('\n');
*/
  /*
  // lead in 500ms
  //Communication_RTTY_TransmitMark();
  //delay(500);
 
  // LTRS
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
 
  Communication_RTTY_TransmitMark();
 
  // R
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitMark();
 
  // LTRS
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitMark();
 
  Communication_RTTY_TransmitMark();
 
  // Y
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitMark();
 
  Communication_RTTY_TransmitMark();
 
  // CR
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitMark();
 
  // LF
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitMark();
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitSpace();
  Communication_RTTY_TransmitSpace();
 
  Communication_RTTY_TransmitMark();
    */
 
  lora.standby();
 
  delay(1000);
}`

![be6e8afd4bbefa57f4d5eedde4481813](https://user-images.githubusercontent.com/1304898/46233914-69942180-c36c-11e8-802f-1b660a747c02.png)

**Comment by jgromes** [comment]
You're initializing the module without any parameters and never changing the bandwidth. Default value is 125 kHz, so this is output seems fine to me. What bandwidth value do you expect?

**Comment by Bambofy** [comment]
Hi we just expect a single peak at 434mhz not sure why there's another peak at the 100khz bandwidth limit?

**Comment by jgromes** [comment]
Because your frequency deviation is (by default) set to 50 kHz - each peak is offset 50 kHz from center frequency. You must set frequency deviation to 0 to get a single peak.

Side note: Judging by your (quite convoluted) code, you're trying to transmit AFSK RTTY. Why not just a normal FSK RTTY? That's the more "standard" approach.

**Comment by Bambofy** [comment]
Thanks for the advice, chose asfk rtty for more backwards compatibility and also kitelib implementation does not decode with mmtty

**Comment by jgromes** [comment]
Were you using ASCII (7 or 8 data bits) or ITA2 (5 bits)?

See https://github.com/jgromes/KiteLib/issues/2

**Comment by Bambofy** [comment]
ITA2 5 bit

**Comment by jgromes** [comment]
ITA2 support was added to KiteLib after initial RTTY implementation; make sure you're using the latest version.
