### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Batarian711** [jgromes/LoRaLib#49]
Hello. I design a logo for open source projects voluntarily. Do you want to help?

**Comment by jgromes** [comment]
Hi, that would be cool! Can you show me some examples of your work? Also, what sort of license would the logo have?

**Comment by Batarian711** [comment]
My logos can visit my profile. Also licensed: http: //creativecommons.org/licenses/by/4.0/

**Comment by jgromes** [comment]
Guess the license won't be an issue then, if the logo is licensed under CC and the rest under MIT.

Do you have some ideas for the logo? I was thinking something like the original LoRa logo. We probably won't be able to use that directly though, since it's trademarked.

**Comment by jgromes** [comment]
Closed due to inactivity, feel free to reopen later.
