### ISSUE TITLE
FSKModem Preamble detector setup

### ISSUE THREAD

**Issue by calinp** [jgromes/LoRaLib#54]
Preamble detection is not set up correctly in configFSK function, SX127x.cpp file, line 1098:

state = _mod->SPIsetRegValue(SX127X_REG_PREAMBLE_DETECT, SX127X_REG_PREAMBLE_DETECT | SX127X_PREAMBLE_DETECTOR_1_BYTE | SX127X_PREAMBLE_DETECTOR_TOL);

The address of the Preamble register ( SX127X_REG_PREAMBLE_DETECT )  is used instead of SX127X_PREAMBLE_DETECTOR_ON bit definition.

**Comment by jgromes** [comment]
Well spotted , thanks!

I checked the rest of the files for similar typos, but it seems that this was the only one.

**Comment by jgromes** [comment]
Fixed in update 7.0.1, thanks for reporting the bug!
