### ISSUE TITLE
FSKModem wrong bit rate setting

### ISSUE THREAD

**Issue by calinp** [jgromes/LoRaLib#55]
Hi, 

In file SX127x.cpp, function setBitRate, line 823, the LSB of the bitrate chosen is written in the MSB register:
  state |= _mod->SPIsetRegValue(SX127X_REG_BITRATE_**MSB**, bitRate & 0x00FF, 7, 0);
should be changed to 
  state |= _mod->SPIsetRegValue(SX127X_REG_BITRATE_**LSB**, bitRate & 0x00FF, 7, 0);

Thank you

**Comment by jgromes** [comment]
Thanks for the report. I don't use the FSK modem all that much, so there might be similar bugs/typos there. It will be fixed in the next release (7.0.2)

**Comment by jgromes** [comment]
Fixed in release 7.1.0, thanks for reporting!
