### ISSUE TITLE
Error code page offline

### ISSUE THREAD

**Issue by juliantech5** [jgromes/LoRaLib#58]
Just a heads up that the https://github.com/jgromes/LoRaLib/wiki/Error-Codes is not in the wiki, not sure if this was intentional but I can't check the error.

Thanks!

**Comment by jgromes** [comment]
Hi, Error codes page was moved to auto-generated docs (alongside the entire documentation). It can be found at https://jgromes.github.io/LoRaLib/group__status__codes.html
