### ISSUE TITLE
Wiring on LoLin NodeMCU Esp8266

### ISSUE THREAD

**Issue by lbrutti** [jgromes/LoRaLib#7]
Hello,
thanks for this library :)

I'm trying to run the examples on  a LoLin NodeMCU with Arduino IDE compatible firmware but with no success, has anyone tried?

Which pin should i connect?

I tried the following connections:

|DRF 1276 DM | NodeMCU|
|----------------|------------|
|       RX            | TXD0    |
|       TX            | RXD0    |
|       GND            | GND    |
|       VCC            | 3v   |
|       EN            | GND    |

Here's the pin diagram of the board
 [https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.myduino.com%2Fimage%2Fdata%2FArduino%2Fnodemcu-002.jpg&f=1](url)
![image](https://user-images.githubusercontent.com/5331258/39004719-71dcd744-43fe-11e8-8b68-de7608dfeafd.png)

And here's the board i'm trying to use:
https://www.tindie.com/products/DORJI_COM/868mhz-915mhz-sx1276-data-radio-modem-drf1276dm/
![image](https://user-images.githubusercontent.com/5331258/39004784-9cee70f0-43fe-11e8-891e-456b52281ecd.png)

Thanks,
Lorenzo

**Comment by jgromes** [comment]
This library uses SPI bus to communicate with the SX127x chips, it won't work with modules that use UART. There was a similar issue with RN2903 modules (see #3).

**Comment by lbrutti** [comment]
thanks for the reply, so no chance to get it work on nodeMcu.

thank you, i'll switch to arduino boards then ;)

**Comment by jgromes** [comment]
I think you misunderstood: the problem is not NodeMCU, the problem is the LoRa module. It uses UART to communicate with the outside world - LoRaLib requires SPI communication, so you need a module like this one: https://www.tindie.com/products/DORJI_COM/arduino-433mhz-lora-sx1278-module-drf1278f/

The library works just fine on NodeMCU.

**Comment by lbrutti** [comment]
uh, ok. do you know any library that can handle UART protocol? i can't change LoRa module at the moment (sorry for the OT)

**Comment by jgromes** [comment]
The code is a basic SoftwareSerial communication example - it will let you directly send data to the LoRa module from Arduino Serial Monitor, so you actually don't need any SX1276 library. From this: http://www.instructables.com/id/Get-Started-With-UM402-LoRa-433MHz-UART-Using-Ardu/ it looks like the module will immediately transmit anything that arrives by the serial line.

According to this doc http://dorji.com/docs/app/ADW1014_Testing_Data_Radio_Modem_With_Serial_Port_Tool.pdf the module probably accepts some form of commands over the serial line, but I don't know any library that can handle that, so you won't be able to change the SX1276 configuration.
