### ISSUE TITLE
Advice on E32-TTl-100

### ISSUE THREAD

**Issue by sekisek** [jgromes/LoRaLib#72]
Hi,

I have this

https://github.com/Bob0505/E32-TTL-100/raw/master/Module.jpg

working with this project:
https://github.com/Bob0505/E32-TTL-100

will that work with your project as well?

thanks

**Comment by jgromes** [comment]
This module does not have access to the SX1278, and it has its own UART interface. LoRaLib only supports plain LoRa radios, from the SX127x or RFM9x series - see [Supported modules](https://github.com/jgromes/LoRaLib/wiki/Supported-LoRa-modules).
