### ISSUE TITLE
ERR_SPI_WRITE_FAILE

### ISSUE THREAD

**Issue by GusakIurii** [jgromes/LoRaLib#73]
Good day.
I used the library LoRaLib version = 7.1.1.
Arduino IDE 1.8.4
Developer's board TTGO LoRa 433MHZ SX1278 MEGA328 (http://www.lilygo.cn/claprod_view.aspx?TypeId=21&Id=539)
Initialization with such parameters:
 lora.begin (434.0, 125.0, 12, 5, 0x12);
In my user program, when sending data (StateTransmit = lora.startTransmit (WriteByte, 2);) the message sometimes appears: "StateTransmit failed, code -16!", I understand this is an error of sending data on SPI (ERR_SPI_WRITE_FAILE). All SPI connections are ok.
But after this error, the program refuses to continue to work, and the next time it is sent, it constantly gives the same error Transmit failed, code -16 !.
Successful sending can be restored after resetting the Mega328p controller.
Can you please tell me how you can programmatically re-initialize SPI, the Lora SX1278 chip, can something else, without waiting for the controller to restart?

11: 02: 12.661> StartTransmit!
11: 02: 12.661>
11: 02: 12.725> address: 0x1
11: 02: 12.725> bits: 2 0
11: 02: 12.725> value: 0b11
11: 02: 12.725> current: 0b10001001
11: 02: 12.725> mask: 0b111
11: 02: 12.784> new: 0b10001011
11: 02: 12.784> read: 0b1111
11: 02: 12.784>
11: 02: 12.848> StartTransmit failed, code -16!

After updating LoRaLib library to version = 8.0.3
This error appears less frequently.
But at some point, the data simply stops being sent, returning the ERR_NONE code

**Comment by jgromes** [comment]
Could you share your code? Nothing in the library should be causing communication to stop after one SPI write failure.

You can reset the LoRa module by pulling the RST pin low for more than 100 us, then releasing it and waiting for 5 ms. See SX1278 datasheet section 7.2.2.

**Comment by GusakIurii** [comment]
`#include <LoRaLib.h>
#include "timer-api.h"
#include <EEPROM.h>
/*
// create instance of LoRa class using SX1278 module
// this pinout corresponds to RadioShield
// https://github.com/jgromes/RadioShield
// NSS pin:   10 (4 on ESP32/ESP8266 boards)
// DIO0 pin:  2
// DIO1 pin:  3
// IMPORTANT: because this example uses external interrupts,
//            DIO0 MUST be connected to Arduino pin 2 or 3.
//            DIO1 MAY be connected to any free pin 
//            or left floating.
*/
SX1278 lora = new LoRa;

byte WriteByte[] = {0, 0};
byte ReadByte[] = {0, 0, 0, 0, 0, 0};
char buf[80];
int  StateRecive;
int  StateTransmit;
int  StateInit;
bool SendOK = false;
bool ReciveOK = false;
bool Transmitt = false;
bool Recive = false;
bool StartRecive = false;
bool WakeUp = false;

//Активация автоматического режима
bool EnableAuto ;

unsigned long  Timeloop=0;

//Выключение включенных клапанов
bool OffValve1 = false;
bool OffValve2 = false;

byte TimerOffValve1 = 0;
byte TimerOffValve2 = 0;

byte NumValveOn1=1;
byte NumValveOn2=21;

byte LastValveOn1=0;
byte LastValveOn2=0;

byte CurrentValveOn1=0;
byte CurrentValveOn2=0;

bool FirtSend1 = false;
bool FirtSend2 = false;


//Номер клапана для опроса 

byte TimerRepeat = 0;
bool RepeatSend = false;
byte CountSend = 0;
String ReadStr = "";
int _timer1 = TIMER_DEFAULT;
 

// Флаг отображает что данные отправлены. (flag to indicate that a packet was received)
volatile bool transmittedFlag = true;
// Флаг отображает что встали в прием.
volatile bool startreceivedFlag = false;
// Флаг отображает что данные пришли. 
volatile bool receivedFlag = false;
volatile bool SendData = false;


//Основные настройки
void setup() {
  
  Serial.begin(9600);
  
  // initialize SX1278 with default settings
  Serial.println(F("GateWay initializing!"));
  // carrier frequency:                   434.0 MHz
  // bandwidth:                           125.0 kHz
  // spreading factor:                    9
  // coding rate:                         7
  // sync word:                           0x12
  // output power:                        17 dBm
  // current limit:                       100 mA
  // preamble length:                     8 symbols
  // amplifier gain:                      0 (automatic gain control)
  //int state = lora.begin();
  int StateInit = lora.begin(434.0, 125.0, 12, 5, 0x12);
  if (StateInit == ERR_NONE) {
    Serial.println(F("GateWay init success!"));
  } else {
    while (StateInit != ERR_NONE)
    {
      Serial.print(F("GateWay init failed, code:"));
      Serial.print(StateInit);
      Serial.println("!");
      StateInit = lora.begin(434.0, 125.0, 12, 5, 0x12);
      delay(1000);
     }
    if (StateInit == ERR_NONE) {
    Serial.println(F("GateWay init success!"));
  }
  }

  // set the function that will be called 
  // when packet transmission is finished
  lora.setDio0Action(setFlag);
  lora.startReceive();
  Recive = true; 
  startreceivedFlag = false; 
  Serial.println(F("GateWay Start Recive!"));
  
  timer_init_ISR_1Hz(_timer1);

 
  EEPROM.get(0, EnableAuto);
  Serial.print(F("Enable Auto:"));
  if (EnableAuto) Serial.print(F("On")); 
  else Serial.print(F("Off"));
  Serial.println(F("!"));
  
  }
void(* resetFunc) (void) = 0;


void timer_handle_interrupts(int timer) {
  if (OffValve1 && !SendData) {
    if  (TimerOffValve1 >= 10)
    {
      OffValve1 = false;
      TimerOffValve1 = 0;
      if (LastValveOn1 != 0) {
      ResetFLAG(LastValveOn1,"Off");
      }

    } else ++TimerOffValve1; 
  }

  if (OffValve2 && !SendData) {
     if  (TimerOffValve2 >= 10)
     {
      OffValve2 = false;
      TimerOffValve2 = 0;
      if (LastValveOn2 != 0) {
      ResetFLAG(LastValveOn2,"Off");
      }
     } else ++TimerOffValve2; 
  }
  
  if (SendData && !RepeatSend) {
      if (TimerRepeat >= 3) {
        TimerRepeat = 0;
        RepeatSend = true;
      }
     else TimerRepeat =  TimerRepeat + 1; 
  }
}

//Фукнция чтения флага
void setFlag(void) {
  // packet transmission is finished, set the flag
  if (Transmitt) 
  {
      Transmitt = false;
      transmittedFlag = true;
  }
  if (Recive)
  {
    receivedFlag = true;
  }

   if (StartRecive)
  {
    startreceivedFlag = true;
  }
  
 }

//функция чтения с Serial 
int readline(int readch, char *buffer, int len) {
    static int pos = 0;
    int rpos;

    if (readch > 0) {
        switch (readch) {
            case '\r': // Ignore CR
                break;
            case '\n': // Return on new-line
                rpos = pos;
                pos = 0;  // Reset position index ready for next time
                return rpos;
            default:
                if (pos < len-1) {
                    buffer[pos++] = readch;
                    buffer[pos] = 0;
                }
        }
    }
    return 0;
}

void ResetFLAG (int adrr, String OnOff){   

    if (OnOff == "Off") { 
    //ValveArray[adrr] = false;
    WriteByte[0] = 48+adrr;
    WriteByte[1] = 0x30;
    }
    
    if (OnOff == "On") { 
    //ValveArray[adrr] = true;
    WriteByte[0] = 48+adrr;
    WriteByte[1] = 0x31;
    }
        
    if (OnOff == "Req") { 
    //ValveArray[adrr] = false;
    WriteByte[0] = 48+adrr;
    WriteByte[1] = 0x32;
    }
         
    if (OnOff == "ReqAll") { 
    //ValveArray[adrr] = false;
    WriteByte[0] = 0x30;
    WriteByte[1] = 0x32;
    }   

    if (OnOff == "ALLPowerOFF") { 
    WriteByte[0] = 0x30;
    WriteByte[1] = 0xFF;
    }

    if (OnOff == "PowerOFF") { 
    WriteByte[0] = 48+adrr;
    WriteByte[1] = 0xFF;
    }

    
    SendOK = false;
    receivedFlag = false;
    Recive = false;
    transmittedFlag = false;
    SendData = true;
    Transmitt = true;
}
            
//функция анализа прочитанных данных с Serial 
void ChekInData (){
    if (!SendData && readline(Serial.read(), buf, 80) > 0) {
         byte addr = 0;
                
        if (String(buf) == "ValveReqAll"){
            ResetFLAG(0,"ReqAll");
            Serial.print("Valve Request All");
            Serial.println("!");          
        } else
 
        if (String(buf) == "EnableAutoOn"){
            EnableAuto = true;
            Serial.print("Enable Auto:");
            Serial.print("On");
            Serial.println("!");
            FirtSend1 = true;  
            FirtSend2 = true; 

            EEPROM.put(0, EnableAuto); 
        } else   
         
        if (String(buf) == "EnableAutoOff"){
            EnableAuto = false;  
            Serial.print("Enable Auto:");
            Serial.print("Off");
            Serial.println("!"); 
            EEPROM.put(0, EnableAuto);       
        } else 

        if (String(buf).startsWith("NumValveOn1")){
            NumValveOn1 = strtol((char*)buf + 12, NULL, 10);
            NumValveOn1 = constrain(NumValveOn1, 1, 20);
            Serial.print("NumValveOn1:");
            Serial.print(NumValveOn1);
            Serial.println("!");
        } else   

        if (String(buf).startsWith("NumValveOn2")){
            NumValveOn2 = strtol((char*)buf + 12, NULL, 10);
            NumValveOn2 = constrain(NumValveOn2, 21, 40);
            Serial.print("NumValveOn2:");
            Serial.print(NumValveOn2);
            Serial.println("!");
        } else 
                 
        if (String(buf) == "ALLPowerOFF"){
            ResetFLAG(0,"ALLPowerOFF");            
            Serial.print("ALLPower:");
            Serial.print("OFF");
            Serial.println("!");          
        } else  

        if (String(buf).startsWith("PowerOFF:")){
            byte addr = strtol((char*)buf + 9, NULL, 10);
            addr = constrain(addr, 1, 40);
            ResetFLAG(addr,"PowerOFF");            
            Serial.print("PowerOFF:");
            Serial.print(addr);
            Serial.println("!");          
        } else 
        
        if (String(buf) == "WakeUpOn"){
            WakeUp = true;  
            Serial.print("WakeUp:");
            Serial.print("On");
            Serial.println("!");      
        } else 

        if (String(buf) == "WakeUpOff"){
            WakeUp = false;  
            Serial.print("WakeUp:");
            Serial.print("Off");
            Serial.println("!");      
        } else 

  
        if (String(buf).startsWith("AllValveOff")){
            ResetFLAG(0,"AllValveOff");            
            Serial.print("AllValveOff");
            Serial.println("!");          
        } else

                
        if (String(buf).startsWith("AllValveOn")){
            ResetFLAG(0,"AllValveOn");            
            Serial.print("AllValveOn");
            Serial.println("!");          
        } else
        
        {
            Serial.print("NOT FOUND:");
            Serial.print(buf);
            Serial.println("!");

            WriteByte[0] = 0;
            WriteByte[1] = 0;          
         }
    }   
}
        
//Отправка данных радиоканала
void WriteData(){
    //Если сейчас нет отправки, и пакет еще небыл корректно отправлен то отправить заново.
  if(!transmittedFlag && Transmitt && !SendOK)  {
    SendOK = true; 
     
    StateTransmit = lora.startTransmit(WriteByte, 2);
    // NOTE: when using interrupt-driven transmit method,
    //       it is not possible to automatically measure
    //       transmission data rate using getDataRate()
    while (StateTransmit != ERR_NONE) {
      Serial.print(F("StateTransmit failed, code "));
      Serial.print(StateTransmit);
      Serial.println("!");
     
      delay(1000);
      //resetFunc();
      while(1);

    } 
      StartRecive = true;
      Serial.print("Transmitted-");
      Serial.print(WriteByte[0]-48);
      Serial.print(":");
      if (WriteByte[1] == 0x30) Serial.println("OFF");     
      if (WriteByte[1] == 0x31) Serial.println("ON");
      if (WriteByte[1] == 0x32) Serial.println("Req");
      if (WriteByte[1] == 0xFF) Serial.println("PowerOFF");     
      if (WriteByte[1] == 0x00) Serial.println("WakeUp");
      //Serial.println("Ok!");
      //if (ValveArray[1])  {Serial.println("ValveArray-On");} else {Serial.println("ValveArray-OFF");}
    
   }
}

//Чтение данных радиоканала
void ReadData(){
    // check if the flag is set
    if(transmittedFlag && SendOK && StartRecive) { 
      StateRecive = lora.startReceive();   
      StartRecive = false; 
      //transmittedFlag = false; 
    }
   if(startreceivedFlag) {
      Serial.println("Start Recive!");
      Recive = true; 
      startreceivedFlag = false;
      TimerRepeat = 0; 
       
   } 
   if(receivedFlag) {  
      receivedFlag = false;
      SendOK=false;
      StateRecive = lora.readData(ReadByte, 6);
     // Voltage = ReadByte
      //ReadData = ReadByte
      ReadStr = String((char*)ReadByte);


      if (StateRecive == ERR_NONE) {
      // packet was successfully received
      //Serial.println("Received packet!");
      if (ReadByte[0] == WriteByte[0] && ReadByte[1] == WriteByte[1]) {ReciveOK = true;} else {ReciveOK = false;}
     
      if (!ReciveOK)
      {
        Serial.print("ReciveERR:");
        Serial.print(byte(ReadByte[0]));
        Serial.println(byte(ReadByte[1]));

      }
      
      Serial.print("Adress:");
      Serial.println(ReadByte[0]-48);
      
      if (ReadByte[1] ==  0x31) {
        Serial.print("Valve-");
        Serial.print(ReadByte[0]-48);
        Serial.print(":");    
        Serial.println("ON");
        }
      
      if (ReadByte[1] ==  0x30) {
        Serial.print("Valve-");
        Serial.print(ReadByte[0]-48);
        Serial.print(":");
        Serial.println("OFF");
        }  
      
      if (ReadByte[1] ==  0xFF) {
        Serial.print("Valve-");
        Serial.print(ReadByte[0]-48);
        Serial.print(":");
        Serial.println("POWER-OFF");
        }    
      if (ReadByte[1] ==  0x00) {
        Serial.print("Valve-");
        Serial.print(ReadByte[0]-48);
        Serial.print(":");
        Serial.println("Wake-UP");
        } 
       if (ReadByte[1] ==  0xFE) {
        Serial.print("Valve-");
        Serial.print(ReadByte[0]-48);
        Serial.print(":");
        Serial.println("Req-Wake");
        }         
      

      // print RSSI (Received Signal Strength Indicator) 
      Serial.print("RSSI-");
      Serial.print(ReadByte[0]-48);
      Serial.print(":");        
      Serial.print(lora.getRSSI());
      Serial.println("dBm");
  
      // print SNR (Signal-to-Noise Ratio) 
      Serial.print("SNR-");
      Serial.print(ReadByte[0]-48);
      Serial.print(":");        
      Serial.print(lora.getSNR());
      Serial.println("dB");

      // print frequency error
      Serial.print("FreqERR-");
      Serial.print(ReadByte[0]-48);
      Serial.print(":");        
      Serial.print(lora.getFrequencyError());
      Serial.println("Hz");
      
      Timeloop = millis()- Timeloop;
      Serial.print("Timeloop:");
      Serial.println(Timeloop);    
      Timeloop = millis();
      
      Serial.println("END");
      
      SendData = false;
      CountSend = 0;

      
      
    } else if (StateRecive == ERR_CRC_MISMATCH) {
      // packet was received, but is malformed
      Serial.println("GateWay Read CRC error!");
      delay(1000);
  
    }
  } else if (SendData && RepeatSend)
    {
      CountSend = CountSend +1;
      RepeatSend = false;
      if (CountSend <= 2) {
          Serial.print("Adress:");
          Serial.println(WriteByte[0]-48);
          Serial.print("Reqest:");
          Serial.println(CountSend);
          Serial.print("Valve-");
          Serial.print(WriteByte[0]-48);
          Serial.print(":"); 
          Serial.println("NO RESPONSE!");
          Serial.println("END");
          SendOK = false;
          receivedFlag = false;
          Recive = false;
          transmittedFlag = false;
          Transmitt = true;
        }
      else {
          SendData = false;
          Serial.print("Adress:");
          Serial.println(WriteByte[0]-48);
          Serial.print("Reqest:");
          Serial.println(CountSend);
          Serial.print("Valve-");
          Serial.print(WriteByte[0]-48);
          Serial.print(":"); 
          Serial.println("NO RESPONSE!");
          Serial.println("END");
          CountSend = 0; 
          if (EnableAuto){ 
            if (WriteByte[0]-48 >= 21) { 
              if (NumValveOn2 >= 40) { 
                NumValveOn2 = 21;
              } else ++NumValveOn2 ;
              
            } else { 
              if (NumValveOn1 >= 20) { 
                 NumValveOn1 = 1;
              } else ++NumValveOn1 ;
            }
          }
            
        }
    }
  
}


//Общая функция
void loop() {
  ChekInData();
  WriteData();
  ReadData(); 
}
`

**Comment by GusakIurii** [comment]
[Send.zip](https://github.com/jgromes/LoRaLib/files/3194192/Send.zip)

**Comment by jgromes** [comment]
On line 368, you have `while(1)` - that's an infinite loop, so the code is working exactly as it should: if `startTransmit()` method returns something other than `ERR_NONE`, the program will enter that infinite loop. Also, line 361 is in itself an infinite loop. Why is there a `while` instead of an `if`?

> The code is too large

I absolutely agree - why not split it into multiple files, or even just strucutre the functions better? Debugging this seems almost impossible.

**Comment by GusakIurii** [comment]
While (1) I set for debugging that this happened.
I think I understood the reason for the failure of spi:
I have several slave devices and one central gateway.
When the slave devices send data to the gateway, and at the same time, the central one also wants to send the data back and it fails. Those. when the central gateway attempts to send data at the time of receiving the data, the SPI fails.
After that, either Laura's chip, or SPI hangs up, and does not respond to commands in any way. I tried to manage the pin directly where RST Lora is connected, but it did not help me:
      delay (10);
      digitalWrite (9, LOW);
      delay (10);
      digitalWrite (9, HIGH);
      delay (10);
      digitalWrite (9, LOW);
      delay (10);
      digitalWrite (9, HIGH);
      delay (10);
      lora.begin (434.0, 125.0, 12, 5, 0x12);
      delay (10);
      lora.startTransmit (WriteByte, 2);

No data was sent after this procedure.

**Comment by jgromes** [comment]
I don't think this is an issue in the library, rather I believe it is somewhere in your code. If you can provide a minimal sketch to reproduce this issue, I will be able to investigate further.
