### ISSUE TITLE
Transreceiver

### ISSUE THREAD

**Issue by MaazSk** [jgromes/LoRaLib#78]
As much as I know LoRa is a trans receiver so I just need some acknowledgement back when the packets are received 

**Is your feature request related to a problem? Please describe.**
I just want your help to make a trans receiver or you can say when my transmission is complete I need some acknowledgement  

**Describe the solution you'd like**
I am having a pair of LoRa Ra-02. I am sending data to another room when the packet is received by the receiver I want, the receiver to send me an acknowledgement back.

**Comment by jgromes** [comment]
From [CONTRIBUTING.md](https://github.com/jgromes/LoRaLib/blob/master/CONTRIBUTING.md):
> **LoRaLib is a driver.**
This means that only features available in the SX127x chips will be implemented. LoRaLib will not implement protocols such as LoRaWAN.

Acknowlegment is not a feature of SX127x, hence it cannot be implemented in the library. It seems very easy to implement on user side - after receiving a packet, send out some short acknowledgement packet (single byte would probably be enough).
