### ISSUE TITLE
Finding the DevAddr of a sending LoRa node

### ISSUE THREAD

**Issue by Y-Fakih** [jgromes/LoRaLib#82]
Hi 

In my final year project, I have to do a selective Jamming Attack on LoRa Devices. In order to do this type of attack, I need to intercept a LoRa message and read the first few bytes to get the DevAddr of the node that sends the LoRa message, then compare this address to my target. If it matches i will alter the transmission and if not i will leave it. 

Is it possible to do such thing using your library ? 
I mean is it possible to read the device address of the Sending LoRa Node ?

Any Type of Help ??
Thank you in advance.

**Comment by jgromes** [comment]
LoRa PHY packets do not have the concept of address. LoRa packet looks like this:

![packet](https://user-images.githubusercontent.com/3407192/59852840-f904b900-936f-11e9-9c54-78cb6f391dc7.png)

Furthermore, assuming the device address is the first byte in payload, SX127x radios do not allow you to start reading the payload before it's fully received. I don't think you will be able to achieve this with hardware LoRa radio, perhaps SDR would be better here?
