### ISSUE TITLE
RF-LORA-915SO-ND based on sx1272

### ISSUE THREAD

**Issue by cerberos19** [jgromes/LoRaLib#83]
Hi, I need to know how the pins of the ESP8266 should be connected to the sx1272 module to 915 Mhz, to be able to use the LoRaLib library and if I have to modify something in the library, I am new to this. I found information to connect to the ESP8266 the modules based on SX1276 / 77/78 (RF95 / 96), but for this module I have not found much information and I do not want to get to damage it

I attach the scheme of the module RF-LORA-915SO-ND to work based on sx1272, taken from the datasheet.

Thank you for your attention.

RF-LORA-915SO-ND based on sx1272
![RF-LORA-915SO-ND-sx1272](https://user-images.githubusercontent.com/52294711/60289947-3bcd1080-98dd-11e9-85f2-233399db6318.PNG)

https://www.digikey.com/product-detail/es/rf-solutions/RF-LORA-915SO/RF-LORA-915SO-ND/5291461
https://media.digikey.com/pdf/Data%20Sheets/RF%20Solutions%20PDFs/RF-LORA.pdf

**Comment by jgromes** [comment]
SX1272 is the same as SX1278 in regards to pin configuration - see https://github.com/jgromes/LoRaLib/wiki/Basics.
