### ISSUE TITLE
Use of D I/O

### ISSUE THREAD

**Issue by MaazSk** [jgromes/LoRaLib#84]
Hi, 
I have a question can you please explain me the use of D I/O pins of the LoRa module as I can't understand it from the datasheet 

Thank you.

**Comment by jgromes** [comment]
The DIO pins are used to signal states of the radio module. For example, in receive mode, when packet is received, DIO0 goes high. If the receive mode times out without packet reception, DIO1 goes high. This is useful as external interrupts for the microcontroller.

DIO state and configuration is handled by the library directly, and users are highly discouraged from manipulating them from Arduino code.

**Comment by MaazSk** [comment]
What is the use of DIO3, DIO4, DIO5?

**Comment by jgromes** [comment]
These - as well as DIO2 - are unused in the library.

It depends on the current mode and configuration. See tables 18, 29 and 30 in SX1278 datasheet.

**Comment by MaazSk** [comment]
Okay 
Thank you!

**Comment by MaazSk** [comment]
Can you explain me How to set DIOx, there is only one pin how can I set it to 00, 01, 10, 11.

**Comment by jgromes** [comment]
Those are the values that are supposed to be written to the SPI registers. For example, to set DIO0 to CadDone event, you have to be in LoRa mode and write value 0b10 to register RegDioMapping1 (0x40) to bits 7 and 6.

**Comment by MaazSk** [comment]
Ohh Okay
Thank You!
