### ISSUE TITLE
Which model of coding is be used?

### ISSUE THREAD

**Issue by moreno-daniel** [jgromes/LoRaLib#93]
I am working with your example “LoRaLib/examples/FSKModem/FSKModem.ino” for data send, and for recibe data the “LoRaLib/examples/ReceiveInterrupt/ReceiveInterrupt.ino”, these projects works good, but my question is: Which model of coding is be used? (Manchester, NRZ, etc).

**Comment by jgromes** [comment]
LoRaLib leaves the default encoding, which is whitening with polynomial x^9 + x^5 + 1 (according to the datasheet section 4.2.13.7 page 78 - 79).
