### ISSUE TITLE
Setting sync word - incorrect registers?

### ISSUE THREAD

**Issue by sjd227** [jgromes/LoRaLib#96]
I think there's a bug setting the sync word to the correct registers. 

In sx127x.cpp, under `int16_t SX127x::setSyncWord(uint8_t* syncWord, size_t len)`, it looks like all bytes of the sync word are only written to RegSyncValue1 (line 804):

`  _mod->SPIwriteRegisterBurst(SX127X_REG_SYNC_VALUE_1, syncWord, len);`

However, each byte of `syncWord` should be written to `RegSyncValue1` through `RegSyncValue8` respectively (see screenshot of sx1272 datasheet below). 

![sync-word-registers-screenshot](https://user-images.githubusercontent.com/6798187/74554756-7db3d100-4f17-11ea-8ac1-3055f74ae94d.png)

**Comment by jgromes** [comment]
The method used there is `SPIwriteRegisterBurst` - it will write in "burst" mode, i.e. write `len` bytes of data to `len` registers, starting at `SX127X_REG_SYNC_VALUE_1`. It's more convenient and faster than calling `SPIwriteRegisterBurst` multiple times.

**Comment by sjd227** [comment]
Got it - thanks!
